apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-react-store.fullname" . }}
  labels:
    app: {{ include "my-react-store.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-react-store.name" . }}
